// Context Jackpot
export const INICIAR_JUEGO = 'INICIAR_JUEGO';
export const SALIR_JUEGO = 'SALIR_JUEGO';
export const REINICIAR_JUEGO = 'REINICIAR_JUEGO';
export const ESTABLECER_IMAGENES = 'ESTABLECER_IMAGENES';
export const DISMINUIR_INTENTOS = 'DISMINUIR_INTENTOS';
export const ESTABLECER_INTENTOS = 'ESTABLECER_INTENTOS';

// Context Alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';
